Add event dispatcher
HippoBaro/R-Type pull request #35
Opened 2016-11-22 15:52 UTC by aguadoenzo

2016-11-22 15:56 UTC, HippoBaro requested changes
Ajouter un moyen de se désinscrire

2016-11-22 18:26 UTC, aguadoenzo commented
Now with a `Unsubcribe(Event)` method

2016-11-22 18:38 UTC, HippoBaro submitted a review, later dismissed

2016-11-22 18:39 UTC, HippoBaro commented
Bon j'accepte le PR mais je te cache pas que c'est assez laid ^^ 💩

2016-11-22 19:31 UTC, aguadoenzo commented
Je sais, je vais le refaire..

2016-11-24 14:12 UTC, aguadoenzo commented
Indeed, je m'en occupe ce soir

2016-11-26 13:52 UTC, aguadoenzo commented
@HippoBaro @Deeganx3 RTM ?

2016-11-26 18:27 UTC, EtiennePasteur approved these changes
Il faudra pas oublier le TODO : class IEntity;
Sinon LGTM

2016-11-26 22:04 UTC, HippoBaro commented
Merci de déplacer tes header dans le dossier include.

2016-11-27 13:28 UTC, merged