Kb socket linux #6
HippoBaro/R-Type pull request #41
Opened 2016-11-27 09:32 UTC by glacecise

2016-11-27 13:05 UTC, aguadoenzo requested changes

2016-11-27 13:05 UTC, aguadoenzo commented on .gitignore
> +Supprimerait .idea/
Si tu veux mettre un commentaire n'oublie pas le `#` devant.
Et pourquoi ça supprimerait .idea ?

2016-11-27 13:05 UTC, aguadoenzo commented on Client/UnitTests/TestTests/Module1.cpp
>  }
Je pense que tu peux virer ce test, c'était juste pour le setup

2016-11-27 13:05 UTC, aguadoenzo commented on Shared/CMakeLists.txt
> +#add_executable(SharedUnitTests ${SHARED_SOURCE_FILES})
Vire les commentaires inutiles

2016-11-27 13:05 UTC, aguadoenzo commented on Shared/src/RTypeSocket.cpp
> +#include "RTypeSocket.hpp"
On met le code dans les .cpp (sauf pour les classes template)

2016-11-27 13:05 UTC, aguadoenzo commented on Shared/src/RTypeSocket.hpp
> +    virtual void InitConnection() {
Why is this method `virtual` ?

2016-11-27 13:05 UTC, aguadoenzo commented on Shared/src/RTypeSocket.hpp
> +//            if (_actual_client != &_clients[i])
Useless comments

2016-11-27 13:05 UTC, aguadoenzo commented on Shared/src/RTypeSocket.hpp
> +            std::cerr << "key press is not compatiblex" << std::endl;
Probablement une faute ici

2016-11-27 13:05 UTC, aguadoenzo commented on Shared/src/RTypeSocket.hpp
> +        if (FD_ISSET(STDIN_FILENO, &_rdfs))
(Commentaire personnel, mais si tu peux mettre des commentaires pour expliquer les `FD_ISSET` et autres ce serait cool :) )

2016-11-27 13:05 UTC, aguadoenzo commented on Shared/src/clienttest.cpp
> +}
Non, ce n'est pas comme ça que les tests marchent. Utilise les macros `TEST` de google test, et mets ton fichier de test dans un dossier à part (regarde sur la branche `developement` pour voir comment c'est fait)

2016-11-27 13:05 UTC, aguadoenzo commented on Shared/src/servertest.cpp
> +}
Idem, voir commentaire précédent, les tests ne marchent pas comme ça

2016-11-27 13:05 UTC, aguadoenzo commented on UnitTests/googletest/googlemock/docs/CookBook.md
> +simplify this interface, we'll need to fix all _clients depending on
Fais attention quand tu refactor avec CLion

2016-11-27 13:05 UTC, aguadoenzo commented
Et règle tes conflits avec `developement` (si tu as besoin d'aide n'hésite pas à demander)

2016-11-27 13:41 UTC, HippoBaro requested changes

2016-11-27 13:41 UTC, HippoBaro commented on Shared/CMakeLists.txt
> +#add_executable(SharedUnitTests ${SHARED_SOURCE_FILES})
Pourquoi changer les règles du CMakeFile SHARED ? Pourquoi créer des binaires ?
Merci de revenir aux bonnes règles en ajoutant tes sources.

2016-11-27 13:41 UTC, HippoBaro commented on Shared/src/IRTypeSocket.hpp
> +#endif //RTYPE_SERVER_IRTYPESOCKET_HPP
Merci d'éviter les interface inutiles.
Le soucis c'est que celle-là est très importante et que là, elle est vide.

2016-11-27 13:41 UTC, HippoBaro commented on Shared/src/RTypeSocket.hpp
> +#define BUF_SIZE 1500
Ces infos n'ont pas leurs place ici. Et pourquoi forcer une valeur `const` ?

2016-11-27 13:41 UTC, HippoBaro commented on Shared/src/RTypeSocket.hpp
> +}   Client;
Ton `socket` n'a rien à voir avec les clients. Je te l'avais dit pourtant.

2016-11-27 13:41 UTC, HippoBaro commented on Shared/src/RTypeSocket.hpp
> +    }
Rien à faire ici

2016-11-27 13:41 UTC, HippoBaro commented on Shared/src/RTypeSocket.hpp
> +    }
Idem.

2016-11-27 13:41 UTC, HippoBaro commented on Shared/src/RTypeSocket.hpp
> +    }
Rien à faire ici.

2016-11-27 13:41 UTC, HippoBaro commented on Shared/src/RTypeSocket.hpp
> +    }
Tu ne devrait pas avoir deux méthodes `ReadClient` et `ReadServer` mais abstraire tel que j'ai une seule fonction `Read`.

2016-11-27 16:13 UTC, aguadoenzo commented on Shared/CMakeLists.txt
> +#add_executable(SharedUnitTests ${SHARED_SOURCE_FILES})
En effet, il n'y a aucun intérêt à faire un binaire étant donné que c'est une librairie partagée

2016-11-27 16:15 UTC, glacecise commented on .gitignore
> +Supprimerait .idea/
j'ai pas touché à ça

2016-11-27 16:17 UTC, glacecise commented on Shared/src/RTypeSocket.hpp
> +}   Client;
et je test comment ?

2016-11-27 16:20 UTC, aguadoenzo commented on .gitignore
> +Supprimerait .idea/
C'est dans ton commit, donc visiblement si

2016-11-27 16:22 UTC, aguadoenzo commented on Shared/src/RTypeSocket.hpp
> +}   Client;
Tu n'as pas a adapter la logique du code pour faire des tests, c'est l'inverse !
Tu as reçu une interface à implémenter, tu fais tes tests comme tu veux pour qu'ils respectent l'implémentation de cette interface

2016-11-27 16:25 UTC, aguadoenzo commented
Petite remarque aussi, essaye de donner des noms clairs et explicites à tes commits (en détaillant ce que tu fais dans ledit commit)

2016-11-27 17:41 UTC, neudinger commented on .gitignore
> +Supprimerait .idea/
ben non

2016-11-27 17:46 UTC, aguadoenzo commented on .gitignore
> +Supprimerait .idea/
C'est comme ça que marche git. Ce changement n'est pas présent dans `development` mais existe dans ta branche, or personne à part toi n'y a touché.
C'est probablement involontaire (je pense à un refactor de CLion), mais ça vient de ton travail dans tous les cas. Donc si tu n'as pas fait ces changements, je t'invite à faire un autre commit qui supprime ces changements

2016-11-27 21:36 UTC, Deeganx3 commented on Shared/src/RTypeSocket.cpp
> +#include "RTypeSocket.hpp"
My Bad, c'est moi qui lui ai dit qu'on fessait du hpp only au début du projet. Mes excuses barre_k.

2016-12-05 12:49 UTC, aguadoenzo requested changes

2016-12-05 12:49 UTC, aguadoenzo commented on .gitignore
> +Shared/src/servertest.cpp
Pourquoi ?

2016-12-05 12:49 UTC, aguadoenzo commented on Client/UnitTests/TestTests/Module1.cpp
>  }
Tu peux le virer

2016-12-05 12:49 UTC, aguadoenzo commented on Shared/CMakeLists.txt
> +add_executable(SharedUnitTests ${SHARED_SOURCE_FILES})
Ne mets pas d’exécutable ici, on compile une libraire !

2016-12-05 12:49 UTC, aguadoenzo commented on Shared/src/RTypeSocket.cpp
> +#include "RTypeSocket.hpp"
Pourquoi ce fichier est vide ?

2016-12-05 12:49 UTC, aguadoenzo commented on Shared/src/RTypeSocket.hpp
> +        std::cout << "clients socket" << _payload->_sock << std::endl;
Pas très utile de logger ça

2016-12-05 12:49 UTC, aguadoenzo commented on Shared/src/RTypeSocket.hpp
> +                std::cout << "i am client i recieve from server" << std::endl;
Pas de code de debug

2016-12-05 12:49 UTC, aguadoenzo commented on Shared/src/RTypeSocket.hpp
> +                std::cout << "i am server i recieve from client" << std::endl;
Pareil ici

2016-12-05 12:49 UTC, aguadoenzo commented on Shared/src/RTypeSocket.hpp
> +#endif //R_TYPE_RTYPESOCKET_HPP
Pas de code dans les header ! Tout dans le `.cpp`

2016-12-05 14:44 UTC, aguadoenzo requested changes

2016-12-05 14:44 UTC, aguadoenzo commented on Shared/UnitTests/TestTests/Module1.cpp
> +    server.join();
Non ! Regarde ce qui a déjà été fait, il y en a même un juste en dessous. Utilise un ASSERT_EQ

2016-12-05 14:44 UTC, aguadoenzo commented on Shared/src/IRTypeSocket.hpp
> +//#elif defined (linux)
Pourquoi ces commentaires ?

2016-12-05 14:44 UTC, aguadoenzo commented on Shared/src/RTypeSocketsave.hpp
> +#endif //R_TYPE_RTYPESOCKET_HPP
Arrête les `git add --all`, regarde ce que tu commits

2016-12-05 14:44 UTC, aguadoenzo commented on Shared/src/servertest.cpp
> +
Non, tu n'as pas à modifier le `main()`, regarde comment sont faits les tests

2016-12-05 14:44 UTC, aguadoenzo commented on UnitTests/CMakeLists.txt
> +        gtest.cpp ${CLIENT_TEST_FILES_ABS_G} ${SERVER_TEST_FILES_ABS_G} ${SHARED_TEST_FILES_ABS_G})
Tu dois compiler tes fichiers de test ici

2016-12-05 20:41 UTC, neudinger reviewed
Fin des Sockets

2016-12-09 22:46 UTC, closed without merging