Ep socket linux #6
HippoBaro/R-Type pull request #49
Opened 2016-11-30 20:29 UTC by Deeganx3

Adding socket for linux and windaube in Shared
It works well on linux and maybe on windaube, but i'm not sure !

2016-11-30 20:36 UTC, aguadoenzo approved these changes
Essaye de mettre des `assert` quand il y a une erreur grave (fail de création de sockets)

2016-11-30 20:36 UTC, aguadoenzo commented on Shared/Socket/Linux/RTypeSocket.hpp
> +constexpr uint16_t port() { return 5673; }
Tu peux faire une `constexpr short int toto = 42;`

2016-11-30 21:10 UTC, Deeganx3 commented on Shared/Socket/Linux/RTypeSocket.hpp
> +constexpr uint16_t port() { return 5673; }
C'est fix :)

2016-11-30 21:22 UTC, Deeganx3 commented on Shared/Socket/Linux/RTypeSocket.hpp
> +constexpr uint16_t port() { return 5673; }
fix :)

2016-12-01 13:04 UTC, HippoBaro requested changes
Deux trois trucs

2016-12-01 13:04 UTC, HippoBaro commented on Shared/Socket/Linux/RTypeSocket.cpp
> +        std::cerr << "Binding port " << _port << " failed !" << std::endl;
Quand une erreur survient, on `throw` une `std::runtime_exception(std::string)`. La tu continues l'exécution alors que le reste n'a aucune chance de fonctionner si tu ne peut pas `bind`.
En plus ce n'est pas au socket de décider si on doit print.

2016-12-01 13:04 UTC, HippoBaro commented on Shared/Socket/Linux/RTypeSocket.cpp
>          std::cerr << "Failed to set non-blocking socket !" << std::endl;
Idem

2016-12-01 13:04 UTC, HippoBaro commented on Shared/Socket/Windows/RTypeSocket.cpp
>      memset((&_addr), '\0', (sizeof(_addr)));
Kézaco ?

2016-12-01 13:04 UTC, HippoBaro commented on Shared/Socket/Windows/RTypeSocket.cpp
> +        std::cerr << "Binding port " << _port << " failed !" << std::endl;
`throw`

2016-12-01 13:06 UTC, EtiennePasteur commented on Shared/Socket/Windows/RTypeSocket.cpp
>      memset((&_addr), '\0', (sizeof(_addr)));
Le constructeur prend soit une Ip + port dans le cas d'un client ou bien seulement un port dans le cas du server

2016-12-01 13:07 UTC, EtiennePasteur commented on Shared/Socket/Windows/RTypeSocket.cpp
>      memset((&_addr), '\0', (sizeof(_addr)));
et le memset et la pour "empty" la structure, c'est pour remplacer le bzero en faite

2016-12-01 13:07 UTC, HippoBaro requested changes

2016-12-01 13:07 UTC, HippoBaro commented on Shared/Socket/Includes/RTypeNetworkPayload.h
>  } RTypeNetworkPayload;
Merci de faire des `struct` C++ et non pas des `POCO`.

2016-12-01 13:09 UTC, HippoBaro commented on Shared/Socket/Windows/RTypeSocket.cpp
>      memset((&_addr), '\0', (sizeof(_addr)));
Mais si tu veux empty la string pourquoi ne pas faire `_addr.clear()` ?

2016-12-01 13:15 UTC, Deeganx3 commented on Shared/Socket/Windows/RTypeSocket.cpp
>      memset((&_addr), '\0', (sizeof(_addr)));
c'est pas une string _addr mais une struct

2016-12-01 13:17 UTC, Deeganx3 commented on Shared/Socket/Includes/RTypeNetworkPayload.h
>  } RTypeNetworkPayload;
```typedef struct s_network {
    std::string _ip;
    std::string _payload;
} RTypeNetworkPayload;```
Comme ça ?

2016-12-01 13:22 UTC, HippoBaro commented on Shared/Socket/Includes/RTypeNetworkPayload.h
>  } RTypeNetworkPayload;
En C++, une `struct` et une `class` sont quasiment la même chose. Utilise plutôt une `class` pour modéliser tes données. Attention juste, contrairement aux `struct`, dans une classe les fields sont `private` par défaut.

Et comme ça ça évite les `typedef` tout moche.

2016-12-01 13:23 UTC, HippoBaro commented on Shared/Socket/Windows/RTypeSocket.cpp
>      memset((&_addr), '\0', (sizeof(_addr)));
My bad, ça porte à confusion avec `addr` qui est une `std::string`.

2016-12-01 13:23 UTC, Deeganx3 commented on Shared/Socket/Includes/RTypeNetworkPayload.h
>  } RTypeNetworkPayload;
```
class RTypeNetworkPayload {
public:
    std::string _ip;
    std::string _payload;
};
```
Comme ça du coup ?

2016-12-01 13:26 UTC, HippoBaro commented on Shared/Socket/Includes/RTypeNetworkPayload.h
>  } RTypeNetworkPayload;
Je peux faire mon relou ?

```
class RTypeNetworkPayload {
public:
    const std::string Ip;
    const std::string Payload;

RTypeNetworkPayload(std::string const &ip, std::string const &payload) : Ip(ip), Payload(payload) ;
};
```

Comme ça ton objet est `immutable`.

2016-12-01 13:28 UTC, Deeganx3 commented on Shared/Socket/Includes/RTypeNetworkPayload.h
>  } RTypeNetworkPayload;
Ca me va je fix tout ça et je push 👍

2016-12-01 13:46 UTC, HippoBaro approved these changes

2016-12-01 13:46 UTC, HippoBaro commented
LGTM :shipit:

2016-12-01 13:49 UTC, merged