Nouvelle entité monstre
HippoBaro/R-Type pull request #95
Opened 2016-12-27 18:17 UTC by aguadoenzo

![ennemies](https://cloud.githubusercontent.com/assets/11411723/21505602/1dc9deda-cc69-11e6-9a09-502bf532d7a5.png)

2016-12-28 01:10 UTC, HippoBaro requested changes

2016-12-28 01:10 UTC, HippoBaro commented on SharedLibs/Entities/Monsters/OrbMonster/GraphicOrbMonster.cpp
> +    this->RegisterTrait(Trait::Drawable);
Évite les `this` redondant. Ici le context est implicite.

2016-12-28 01:10 UTC, HippoBaro commented on SharedLibs/Entities/Monsters/OrbMonster/GraphicOrbMonster.cpp
> +        this->setScale(sf::Vector2f(4.0f, 4.0f));
Idem

2016-12-28 01:10 UTC, HippoBaro commented on SharedLibs/Entities/Monsters/OrbMonster/OrbMonster.cpp
> +    return this->ORB_MONSTER;
Quand tu utilise une `enum` déclaré dans une class, utilise plutôt `Entity::ORB_MONSTER`, comme ça on sait d'où ça vient.

2016-12-28 16:30 UTC, EtiennePasteur commented on SharedLibs/Entities/Monsters/OrbMonster/CMakeLists.txt
> +target_link_libraries(DrawableOrbMonster sfml-graphics sfml-window sfml-system)
sfml-sys est vraiment utile ?

2016-12-28 16:31 UTC, EtiennePasteur approved these changes
LGTM

2016-12-29 18:28 UTC, HippoBaro approved these changes

2016-12-29 18:28 UTC, merged